Update github action

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -30,10 +30,20 @@ jobs:
           sudo apt-get install -y google-chrome-stable
           google-chrome --version
 
-      - name: Set up ChromeDriver
-        uses: actions/setup-chromedriver@v1
-        with:
-          chrome-version: '115.0.5790' # Specify the major version of Chrome
+      - name: Install ChromeDriver
+        run: |
+          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
+          MAJOR_CHROME_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f 1)
+          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${MAJOR_CHROME_VERSION})
+          if [ -z "$CHROMEDRIVER_VERSION" ]; then
+            echo "Failed to obtain ChromeDriver version for Chrome version $CHROME_VERSION"
+            exit 1
+          fi
+          wget -N https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
+          unzip chromedriver_linux64.zip
+          sudo mv -f chromedriver /usr/local/bin/chromedriver
+          sudo chmod +x /usr/local/bin/chromedriver
+          chromedriver --version
 
       - name: Run Selenium Standalone Server
         run: |
